// Code generated by MockGen. DO NOT EDIT.
// Source: access-system-api/internal/repository (interfaces: EmbeddingRepository)

// Package mocks is a generated GoMock package.
package mocks

import (
	domain "access-system-api/internal/domain"
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	pgvector "github.com/pgvector/pgvector-go"
)

// MockEmbeddingRepository is a mock of EmbeddingRepository interface.
type MockEmbeddingRepository struct {
	ctrl     *gomock.Controller
	recorder *MockEmbeddingRepositoryMockRecorder
}

// MockEmbeddingRepositoryMockRecorder is the mock recorder for MockEmbeddingRepository.
type MockEmbeddingRepositoryMockRecorder struct {
	mock *MockEmbeddingRepository
}

// NewMockEmbeddingRepository creates a new mock instance.
func NewMockEmbeddingRepository(ctrl *gomock.Controller) *MockEmbeddingRepository {
	mock := &MockEmbeddingRepository{ctrl: ctrl}
	mock.recorder = &MockEmbeddingRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockEmbeddingRepository) EXPECT() *MockEmbeddingRepositoryMockRecorder {
	return m.recorder
}

// CreateEmbedding mocks base method.
func (m *MockEmbeddingRepository) CreateEmbedding(arg0 context.Context, arg1 *domain.Embedding) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateEmbedding", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateEmbedding indicates an expected call of CreateEmbedding.
func (mr *MockEmbeddingRepositoryMockRecorder) CreateEmbedding(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateEmbedding", reflect.TypeOf((*MockEmbeddingRepository)(nil).CreateEmbedding), arg0, arg1)
}

// DeleteEmbeddingById mocks base method.
func (m *MockEmbeddingRepository) DeleteEmbeddingById(arg0 context.Context, arg1 int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteEmbeddingById", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteEmbeddingById indicates an expected call of DeleteEmbeddingById.
func (mr *MockEmbeddingRepositoryMockRecorder) DeleteEmbeddingById(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteEmbeddingById", reflect.TypeOf((*MockEmbeddingRepository)(nil).DeleteEmbeddingById), arg0, arg1)
}

// GetSimilarEmbeddingByVector mocks base method.
func (m *MockEmbeddingRepository) GetSimilarEmbeddingByVector(arg0 context.Context, arg1 pgvector.Vector) (*domain.Embedding, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSimilarEmbeddingByVector", arg0, arg1)
	ret0, _ := ret[0].(*domain.Embedding)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSimilarEmbeddingByVector indicates an expected call of GetSimilarEmbeddingByVector.
func (mr *MockEmbeddingRepositoryMockRecorder) GetSimilarEmbeddingByVector(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSimilarEmbeddingByVector", reflect.TypeOf((*MockEmbeddingRepository)(nil).GetSimilarEmbeddingByVector), arg0, arg1)
}
